import fs from 'node:fs'
import path from 'node:path'
import fg from 'fast-glob'
import { defineBuildConfig } from 'unbuild'

const etsGlobalScopeFiles = fg.sync([
  'ets/component/*.{d.ts,d.ets}',
  'ets/build-tools/ets-loader/declarations/global.d.ts',
], {
  absolute: false,
  onlyFiles: true,
  onlyDirectories: false,
  cwd: __dirname,
}).reduce((acc, file) => {
  acc[file] = fs.readFileSync(path.resolve(__dirname, file), 'utf-8')
  return acc
}, {} as Record<string, string>)

const etsApiFiles = fg.sync([
  'ets/api/**/*.{d.ts,d.ets}',
  'ets/kits/**/*.{d.ts,d.ets}',
  'ets/arkts/**/*.{d.ts,d.ets}',
], {
  absolute: false,
  onlyFiles: true,
  onlyDirectories: false,
  cwd: __dirname,
}).reduce((acc, file) => {
  acc[file] = fs.readFileSync(path.resolve(__dirname, file), 'utf-8')
  return acc
}, {} as Record<string, string>)

fs.writeFileSync(
  path.resolve(__dirname, 'ets.generated.ts'),
  `/* This file is generated by build.config.ts, DO NOT EDIT */
export const etsGlobalScopeFiles = ${JSON.stringify(etsGlobalScopeFiles, null, 2)};
export const etsApiFiles = ${JSON.stringify(etsApiFiles, null, 2)};
`,
)

export default defineBuildConfig({
  entries: [
    'src/index',
    'src/core',
    'src/fallback',
  ],
  declaration: true,
  clean: true,
  rollup: {
    emitCJS: true,
    inlineDependencies: true,
  },
})
